base/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from base import views
from .views import *

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('', TaskList.as_view(), name ='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name ='task'),
    path('task-create/', TaskCreate.as_view(), name ='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name ='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name ='task-delete'),
    path('top-users/', TopUsersView.as_view(), name='top-users'),
    path('about/', About.as_view(), name='about'),
     #path('password/', auth_views.PasswordChangeView.as_view(template_name='base/change-password.html')),
    path('password/', auth_views.PasswordChangeView.as_view(template_name='base/change-password.html')),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path('user_profile/<int:pk>/', ShowProfilePageView.as_view(), name='user_profile'),
    path('edit_profile_page/<int:pk>/',EditProfilePageView.as_view(), name='edit_user_profile'),
    path('create_profile_page/',CreateProfilePageView.as_view(), name='create_user_profile'),
    path('notion/', NotionList.as_view(), name ='notions'),
    path('notion/<int:pk>/', NotionDetail.as_view(), name ='notion_detail'),
    path('notion-create/', NotionCreate.as_view(), name ='notion-create'),
    path('notion/update/<int:pk>/', NotionUpdate.as_view(), name ='notion-update'),
    path('notion/<int:pk>/', NotionDetail.as_view(), name ='notion'),
    path('notion/<int:pk>/delete', DeleteNotiontView.as_view(), name ='notion-delete'),
    path('contact/', views.contact, name="contact")
]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls')),
    path('captcha/', include('captcha.urls')),
    path('base/', include('base.urls')),
    path('', include('shop.urls', namespace='shop')),  # копируем все urls из приложения shop
]
# handler404 = 'base.views.error_404_view'
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    # в режиме отладки добавляем к нашим маршрутам еще один маршрут для статических данных, графических файлов
    # вторым аргументом тут идет папка, где будут идти файлы. На реальных серверах это не нужно, так как уже все настроено
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import order_create

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),

]

shop/urls.py
from django.urls import path

from .views import *

# используем namespacing для удобства. Теперь, к примеру, the product_list URL будет доступен, как shop:product_list в других частях Django проекта.
app_name = 'shop'

urlpatterns = [
    path('', ShopHome.as_view(), name='product_list'),
    path('category/<slug:category_slug>/', ShopCategory.as_view(), name='product_list_by_category'),
    path('category/<slug:category_slug>/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('about/', about, name='about'),
    path('feedback/', FeedbackFormView.as_view(), name='feedback'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('catalog/', catalog, name='catalog'),
]

cart/models.py
"""Для хранения информации о корзине используются сесии"""

cart/forms.py
from django import forms
from django.forms import NumberInput


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(
        min_value=1,
        initial=1,
        widget=forms.HiddenInput()
    )

cart/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import CartAddProductForm
from .cart_services import Cart


class CartDetailView(View):
    def get(self, request):
        cart = Cart(request)
        cart_items = cart.get_cart_items_with_products()
        cart_total_price = cart.get_cart_total_price(cart_items)
        context = {
            'cart': cart_items,
            'cart_total_price': cart_total_price
        }
        return render(request, 'cart/detail.html', context)


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add_to_cart(product_id, cd['quantity'], request.POST.get('overwrite_qty'))
            return redirect('cart:cart_detail')


class CartRemoveView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        cart.remove_from_cart(product_id)
        return redirect('cart:cart_detail')

cart/templates/cart/detail.html
{% load static %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'shop/css/normalize.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/css/base.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/css/basket.css' %}"/>
<link rel="icon" href="{% static 'shop/img/img.png' %}">
{% include 'shop/inc/_header.html' %}
<h1 class="title_basket">{% block title %}Корзина{% endblock %}</h1>

{% block content %}
    {% if cart_total_price > 0 %}
        <ol class="cart_ol">
            {% for item in cart %}
                {% with product=item.product %}
                    <li class="cart-li" role="listitem">
                        <div class="item-info row" tabindex="-1">
                            <div class="item-info-image column large-3" aria-hidden="true">
                                {# Левая часть с фотографией товара #}
                                <a href="{{ product.get_absolute_url }}">
                                <img src="{{ product.image.url }}" alt="" width="400" height="400" aria-hidden="true"></a>
                            </div>
                            <div class="item-info-content column large-9">
                                {# Правая часть с описанием и ценой за товар #}
                                <div class="item-info-details"> {# Название, количество, цена #}
                                    <div class="item-info-title large-6"> {# навзвание #}
                                        <h2 class="item-info-title-details"><a
                                                href="{{ product.get_absolute_url }}">{{ product.title }}</a></h2>
                                    </div>
                                    <div class="item-info-count"> {# Количество #}
                                        <div class="quantity">
                                            <div class="quantity-selector">
                                                <div class="quantity-wrapper form-dropdown">
                                                    {{ item.quantity }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="item-info-price large-last"> {# Цена за товар #}
                                        <div class="item-info-price-details"><p>₽ {{ product.price|intcomma }}</p></div>
                                    </div>
                                </div>
                                <div>{{ product.description }}
                                </div>
                                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="button-delete" type="submit">
                                        <svg viewBox="0 0 448 512" class="svgIcon">
                                            <path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"></path>
                                        </svg>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </li>
                {% endwith %}
            {% endfor %}
        </ol>
        <div class="summary">
            <div class="large-9 large-offset-3">
                <div class="summary-content summary-subtotal">
                    <div class="summary-labelandvaluecontainer">
                        <div class="summary-label">Промежуточный итог</div>
                        <div class="summary-value"> ₽ {{ cart_total_price|intcomma }}</div>
                    </div>
                </div>
                <div class="summary-content summary-shipping">
                    <div class="summary-labelandvaluecontainer">
                        <div class="summary-label">Доставка</div>
                        <div class="summary-value">бесплатно</div>
                    </div>
                </div>
                <div class="summary-labelandvaluecontainer summary-total">
                    <div class="summary-label">Итоговая цена</div>
                    <div class="summary-value"> ₽ {{ cart_total_price|intcomma }}</div>
                </div>
            </div>
        </div>
        <div class="buy">
            <div class="button-div">
                <a class="button-back" href="{% url 'shop:catalog' %}">
                    <svg height="16" width="16" xmlns="http://www.w3.org/2000/svg" version="1.1"
                         viewBox="0 0 1024 1024">
                        <path d="M874.690416 495.52477c0 11.2973-9.168824 20.466124-20.466124 20.466124l-604.773963 0 188.083679 188.083679c7.992021 7.992021 7.992021 20.947078 0 28.939099-4.001127 3.990894-9.240455 5.996574-14.46955 5.996574-5.239328 0-10.478655-1.995447-14.479783-5.996574l-223.00912-223.00912c-3.837398-3.837398-5.996574-9.046027-5.996574-14.46955 0-5.433756 2.159176-10.632151 5.996574-14.46955l223.019353-223.029586c7.992021-7.992021 20.957311-7.992021 28.949332 0 7.992021 8.002254 7.992021 20.957311 0 28.949332l-188.073446 188.073446 604.753497 0C865.521592 475.058646 874.690416 484.217237 874.690416 495.52477z"></path>
                    </svg>
                    <span style="padding-left: 5px">Назад</span>
                </a>
                <a href="{% url 'orders:order_create' %}">
                    <div data-tooltip="Price: ₽{{ cart_total_price|intcomma }}" class="button">
                        <div class="button-wrapper">
                            <div class="text">Оформить заказ</div>
                            <span class="icon">
                    <svg viewBox="0 0 16 16" class="bi bi-cart2" fill="currentColor" height="16" width="16"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>
                    </svg>
                </span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    {% else %}
        <h1>Ваша корзина пуста</h1>
        <a class="button-back" href="{% url 'shop:catalog' %}" style="width: 300px">
            <svg height="16" width="16" xmlns="http://www.w3.org/2000/svg" version="1.1"
                 viewBox="0 0 1024 1024">
                <path d="M874.690416 495.52477c0 11.2973-9.168824 20.466124-20.466124 20.466124l-604.773963 0 188.083679 188.083679c7.992021 7.992021 7.992021 20.947078 0 28.939099-4.001127 3.990894-9.240455 5.996574-14.46955 5.996574-5.239328 0-10.478655-1.995447-14.479783-5.996574l-223.00912-223.00912c-3.837398-3.837398-5.996574-9.046027-5.996574-14.46955 0-5.433756 2.159176-10.632151 5.996574-14.46955l223.019353-223.029586c7.992021-7.992021 20.957311-7.992021 28.949332 0 7.992021 8.002254 7.992021 20.957311 0 28.949332l-188.073446 188.073446 604.753497 0C865.521592 475.058646 874.690416 484.217237 874.690416 495.52477z"></path>
            </svg>
            <span style="padding-left: 5px">Перейти к каталогу</span>
        </a>
    {% endif %}
    <div style="margin-top: 50px">
    {% include 'shop/inc/_footer.html' %}</div>
{% endblock content %}