base/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from base import views
from .views import *

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('', TaskList.as_view(), name ='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name ='task'),
    path('task-create/', TaskCreate.as_view(), name ='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name ='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name ='task-delete'),
    path('top-users/', TopUsersView.as_view(), name='top-users'),
    path('about/', About.as_view(), name='about'),
     #path('password/', auth_views.PasswordChangeView.as_view(template_name='base/change-password.html')),
    path('password/', auth_views.PasswordChangeView.as_view(template_name='base/change-password.html')),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path('user_profile/<int:pk>/', ShowProfilePageView.as_view(), name='user_profile'),
    path('edit_profile_page/<int:pk>/',EditProfilePageView.as_view(), name='edit_user_profile'),
    path('create_profile_page/',CreateProfilePageView.as_view(), name='create_user_profile'),
    path('notion/', NotionList.as_view(), name ='notions'),
    path('notion/<int:pk>/', NotionDetail.as_view(), name ='notion_detail'),
    path('notion-create/', NotionCreate.as_view(), name ='notion-create'),
    path('notion/update/<int:pk>/', NotionUpdate.as_view(), name ='notion-update'),
    path('notion/<int:pk>/', NotionDetail.as_view(), name ='notion'),
    path('notion/<int:pk>/delete', DeleteNotiontView.as_view(), name ='notion-delete'),
    path('contact/', views.contact, name="contact")
]

django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls')),
    path('captcha/', include('captcha.urls')),
    path('base/', include('base.urls')),
    path('', include('shop.urls', namespace='shop')),  # копируем все urls из приложения shop
]
# handler404 = 'base.views.error_404_view'
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    # в режиме отладки добавляем к нашим маршрутам еще один маршрут для статических данных, графических файлов
    # вторым аргументом тут идет папка, где будут идти файлы. На реальных серверах это не нужно, так как уже все настроено
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from .views import *

# используем namespacing для удобства. Теперь, к примеру, the product_list URL будет доступен, как shop:product_list в других частях Django проекта.
app_name = 'shop'

urlpatterns = [
    path('', ShopHome.as_view(), name='product_list'),
    path('category/<slug:category_slug>/', ShopCategory.as_view(), name='product_list_by_category'),
    path('category/<slug:category_slug>/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('about/', about, name='about'),
    path('feedback/', FeedbackFormView.as_view(), name='feedback'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('catalog/', catalog, name='catalog'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError


class Category(models.Model):
    """Модель для категорий товаров"""
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)

    class Meta:
        """Используем для задания параметров в админке, без необходимости добавления новых полей в саму модель. """
        ordering = ('name',)  # сортировка применяется и в отображении в админке и в шаблонах
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    """Модель товаров"""
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Доступность')

    class Meta:
        verbose_name = 'Товары'  # отображение названия в админке
        verbose_name_plural = 'Товары'  # отображение названия в админке
        ordering = ('title',)

    def __str__(self):
        return self.title

    # self ссылка на ЭК модели. Через self обращаемся к нужному атрибуту для формирования динамического url и использования в шаблонах.
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.category.slug,
                                                    self.slug])  # c помощью reverse формируем маршурут с именем shop:product_detail, для этого дополнитнительно  передаем нужные параметры

    def get_average_review_score(self):
        """Вычисляем средний рейтинг товара. self.reviews возвращает все связанные объекты Review для данного объекта Product"""
        average_score = 0.0
        if self.reviews.count() > 0:
            total_score = sum([review.rating for review in self.reviews.all()])
            average_score = total_score / self.reviews.count()
        return round(average_score, 1)


class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')


class Review(models.Model):
    """Модель отзывов."""
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE, verbose_name='Товар')
    author = models.CharField(max_length=50, verbose_name='Автор')
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name='Рейтинг')
    text = models.TextField(blank=True, verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        ordering = ('-created',)

    def save(self, *args, **kwargs):
        if self.rating > 5 or self.rating < 1:
            raise ValidationError("Неверный рейтинг")
        super().save(*args, **kwargs)

shop/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from captcha.fields import CaptchaField

from .models import Review


class RegisterUserForm(UserCreationForm):
    """Форма регистрации пользователей"""
    name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-input'}), min_length=2)
    first_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-input'}), min_length=2)
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}), min_length=2)
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}), min_length=8,
                                error_messages={'min_length': 'Пароль должен быть длиной не менее 8 символов'})
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Пароли не совпадают')
        return password2

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 8:
            raise forms.ValidationError('Пароль должен содержать не менее 8 символов.')
        if password1.isdigit():
            raise forms.ValidationError('Пароль должен содержать хотя бы один символ, кроме цифр.')
        return password1

    class Meta:
        model = User  # связываем форму с встроенной моделью User
        fields = ('name', 'first_name', 'username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    """Форма для аутентификации потльзователей"""
    username = forms.CharField(label='E-mail или логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input', 'type': 'password'}))


class FeedbackForm(forms.Form):
    """Форма обратной связи"""
    name = forms.CharField(label='Имя', max_length=100)
    email = forms.EmailField(label='Email')
    content = forms.CharField(label='Сообщение', widget=forms.Textarea(attrs={'cols': 30, 'rows': 4}))
    capatcha = CaptchaField(label='Введите каптчу с картинки')


class ReviewForm(forms.ModelForm):
    """Форма для оставления отзыва на товар"""

    class Meta:
        model = Review
        fields = ['text', 'rating']
        widgets = {
            'text': forms.Textarea(
                attrs={'class': 'form-control shadow px-2',
                       'rows': 6
                       }
            ),
            'rating': forms.RadioSelect
        }

shop/views.py
from loguru import logger

from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, FormView, DetailView
from .forms import RegisterUserForm, LoginUserForm, FeedbackForm, ReviewForm
from .models import *
from .utils import DataMixin
from cart.forms import CartAddProductForm

logger.add("debug.log", format="{time} {level} {message}", level="DEBUG", rotation="10 MB")


class ShopHome(DataMixin, ListView):
    model = Product
    template_name = 'shop/base.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)  # вызываем родительский метод, чтобы получить базовый контекст
        context['title'] = "Главная"  # добавляем к контексту свои данные, полученные с помощью метода get_user_context
        return dict(list(context.items()))

    def get_queryset(self):
        """Добавляем для оптимизации нагрузки на БД. Благодаря методу select_related у нас происходит
        жадная, а не ленивая загрузка связанных данных  по внешнему FK. В моем случае я уменьшаю количество запросов
        по категориям на главной странице с 11 до 5 (так как в каждом товаре указывается категория)."""
        return Product.objects.all().select_related('category')


class ProductDetailView(DataMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'shop/product/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        other_products = Product.objects.filter(category=category).exclude(pk=self.object.pk)[:5]
        context['category'] = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        context['other_products'] = other_products
        context['review_form'] = ReviewForm()
        context['cart_product_form'] = CartAddProductForm()
        context['gallery_images'] = self.object.images.all()
        context = self.get_user_context(**context)
        return context

    def post(self, request, category_slug, slug):
        product = self.get_object()
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            cleaned_form = review_form.cleaned_data
            author_name = "Анонимный пользователь"
            Review.objects.create(
                product=product,
                author=author_name,
                rating=cleaned_form['rating'],
                text=cleaned_form['text']
            )
            return redirect('shop:product_detail', category_slug=category_slug, slug=slug)

        context = self.get_context_data()
        context['review_form'] = review_form
        return self.render_to_response(context)


class ShopCategory(DataMixin, ListView):
    model = Product
    template_name = 'shop/product/list.html'
    context_object_name = 'products'
    allow_empty = False  # генерация ошибки 404 если  нет товаров в категории

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = str(context['products'][0].category).upper()
        return dict(list(context.items()))

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'shop/product/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Регистрация')
        context['form_first'] = RegisterUser.form_class
        return dict(list(context.items()) + list(user_context.items()))

    def form_valid(self, form):
        """Встроенный метод который вызывается при успешной регистрации.
        Нужен чтобы зарегистрированного пользователя автоматически авторизовывали.
        Отличие от атрибута success_url в том, что через переменную мы не можем
        после успешной регистрации сразу авторизовать, а также  переменную можно только статический
        адрес указать. Если ссылка формируется динамически - только метод подойдет.
        К примеру, Если я например делаю сайт, где у зарегистрированного пользователя
        есть личная страница,  и я хочу что бы она была по адресу mysite/accounts/<никнейм пользователя>"""
        user = form.save()  # самостоятельно сохраняем пользователя в нашу модель в БД.
        login(self.request, user)  # функция для авторизации пользователя
        return redirect('shop:product_list')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm  # тут мы указываем свою кастомную форму. Изначально пользовались встроенной - класс AutenticationForm
    template_name = 'shop/product/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Войти')
        return dict(list(context.items()) + list(user_context.items()))

    def get_success_url(self):
        return reverse_lazy('shop:product_list')


class FeedbackFormView(DataMixin, FormView):
    form_class = FeedbackForm
    template_name = 'shop/product/feedback.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Обратная связь')
        context['form_feedback'] = FeedbackFormView.form_class
        return dict(list(context.items()) + list(user_context.items()))

    def form_valid(self, form):
        logger.debug(form.cleaned_data)  # если форма заполнена корректно, то при отправке логируем данные из формы
        return redirect('shop:product_list')


def about(request):
    return render(request, 'shop/product/about.html')


def logout_user(request):
    logout(request)  # стандартная ф-ия Джанго для выхода из авторизации
    return redirect('shop:login')


def catalog(request):
    prod = Product.objects.all()
    return render(request, 'shop/product/catalog.html', {'prod': prod})

shop/templates/shop/product/about.html
{% load static %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'shop/css/normalize.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/css/about.css' %}"/>
<link rel="icon" href="{% static 'shop/img/img.png' %}">
{% include 'shop/inc/_header.html' %}
{% block content %}
    <div style="height: 500px">
        <h1>О нас</h1>
        <h2>Мы группа 3ИС-20 политехнического колледжа имени Н.Н.Годовикова</h2>
        <h3>Данный проект разработан: </h3>
        <div class="about-div">
            <div><a href="https://github.com/Longin-Khibovskiy" class="name_hub_about">Хибовский Лонгин</a></div>
            <div><a href="https://github.com/Khusainceg77" class="name_hub_about">Хусаинов Руслан</a></div>
            <div><a href="https://github.com/Veronichka-lanyouk" class="name_hub_about">Ланюк Вероника</a></div>
            <div><a href="https://github.com/Strr1t" class="name_hub_about">Ларионов Александр</a></div>
            <div><a href="https://github.com/FuriakAngelika" class="name_hub_about">Фурьяк Анжелика</a></div>
            <div>(Fullstack developer)</div>
            <div>(Backend developer)</div>
            <div>(Frontend developer and designer)</div>
            <div>(Backend developer)</div>
            <div>(Designer)</div>
        </div>
    </div>
{% endblock %}
{% include 'shop/inc/_footer.html' %}

shop/templates/shop/product/catalog.html
{% load static %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'shop/css/normalize.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/css/base.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/css/catalog.css' %}">
<link rel="icon" href="{% static 'shop/img/img.png' %}">
{% include 'shop/inc/_header.html' %}
{% block content %}
    <h1 style="text-align: center; padding-bottom: 60px; font-size: 60px; font-family: Palatino;">Каталог товаров</h1>
    <section class="color">
        <div class="container">
            <div class="color-list">
                {% for prod in prod %}
                    <div class="catalog-card">
                        <div class="color-item">
                            <a href="{{ prod.get_absolute_url }}">
                                <img class="color_img" src="







                                        {% if prod.image %}{{ prod.image.url }}{% else %}{% static 'shop/img/no_image.png' %}{% endif %}">
                            </a>
                            <p class="catalog-title">{{ prod.title }}</p>
                            <p class="catalog-price">{{ prod.price|intcomma }} ₽</p>
                        </div>
                    </div>
                {% empty %}
                    <li>Каталог пуст</li>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}
{% include 'shop/inc/_footer.html' %}

shop/templates/shop/product/feedback.html
{% extends "shop/base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="row">
                <div class="col-5">
                    {{ field.label_tag }}
                </div>
                <div class="col-5">
                    {{ field|as_crispy_field }}
                    <div class="form-error">
                        {{ field.errors }}
                    </div>
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">Отправить</button>
    </form>
    <br>
{% endblock %}

shop/templates/shop/product/login.html
{% load static %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'shop/css/normalize.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/css/detail.css' %}"/>
<link rel="stylesheet" href="{% static 'shop/css/login.css' %}"/>
<link rel="icon" href="{% static 'shop/img/img.png' %}">
<style>
    body {
        background-color: #efefef;
        text-align: center;
    }

    h1 {
        text-align: center;
    }

    ::placeholder {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    }

    form {
        width: 100%;
        align-content: center;
        text-align: center;
    }

    .form-input {
        margin-left: 10px;
        border-radius: 10px;
        border: none;
        width: 100%;
        height: 100%;
    }

    .form-input:focus {
        outline: none;
    }

    .inputForm {
        border: 1.5px solid #ecedec;
        border-radius: 10px;
        height: 50px;
        display: flex;
        align-items: center;
        padding-left: 10px;
        transition: 0.2s ease-in-out;
    }

    .form-input {
        margin-left: 10px;
        border-radius: 10px;
        border: none;
        width: 70%;
        height: 100%;
    }

    .form-input:focus {
        outline: none;
    }

    .inputForm:focus-within {
        border: 1.5px solid #2d79f3;
    }

    .button-submit {
        margin: 20px 0 10px 0;
        background-color: #151717;
        border: none;
        color: white;
        font-size: 15px;
        font-weight: 500;
        border-radius: 10px;
        height: 50px;
        width: 100%;
        cursor: pointer;
    }

    .button-back {
        display: flex;
        height: 3em;
        width: 150px;
        align-items: center;
        justify-content: center;
        background-color: #efefef;
        border-radius: .60em;
        letter-spacing: 1px;
        transition: all 0.2s linear;
        cursor: pointer;
        border: none;
        background: #efefef;
    }

    .button-back > svg {
        margin-right: 5px;
        margin-left: 5px;
        font-size: 20px;
        transition: all 0.4s ease-in;
    }

    .button-back:hover > svg {
        font-size: 1.2em;
        transform: translateX(-5px);
    }

    .button-back:hover {
        box-shadow: 9px 9px 33px #d1d1d1, -9px -9px 33px #ffffff;
        transform: translateY(-2px);
    }
</style>

{% block content %}
    <div style="display: flex">
        <a class="button-back" href="{% url 'shop:catalog' %}" style="width: 300px">
            <svg height="16" width="16" xmlns="http://www.w3.org/2000/svg" version="1.1"
                 viewBox="0 0 1024 1024">
                <path d="M874.690416 495.52477c0 11.2973-9.168824 20.466124-20.466124 20.466124l-604.773963 0 188.083679 188.083679c7.992021 7.992021 7.992021 20.947078 0 28.939099-4.001127 3.990894-9.240455 5.996574-14.46955 5.996574-5.239328 0-10.478655-1.995447-14.479783-5.996574l-223.00912-223.00912c-3.837398-3.837398-5.996574-9.046027-5.996574-14.46955 0-5.433756 2.159176-10.632151 5.996574-14.46955l223.019353-223.029586c7.992021-7.992021 20.957311-7.992021 28.949332 0 7.992021 8.002254 7.992021 20.957311 0 28.949332l-188.073446 188.073446 604.753497 0C865.521592 475.058646 874.690416 484.217237 874.690416 495.52477z"></path>
            </svg>
            <span style="padding-left: 5px">Перейти к каталогу</span>
        </a></div>
    <div class="container" style="margin-top: 100px">
        <div class="row">
            <div class="login wrap">
                <h1 class="h1">Введите данные</h1>
                <br>
                <div style="display: flex; justify-content: center">
                    <form method="post"
                          style="display: flex;flex-direction: column;gap: 10px;background-color: #ffffff;padding: 30px;width: 50%;border-radius: 20px;font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
                        {% csrf_token %}
                        <!-- Отражение общих ошибок авторизации ползователей. Т.е. ошибки связанные не с заполнением полей, напр. неверные логин/пароль-->
                        <div class="form-error">{{ form.non_field_errors }}</div>
                        <!-- Конец -->
                        {% for f in form %}
                            <p class="inputForm">
                                <label class="form-label" for="{{ f.id_for_label }}"> {{ f.label }}: </label>{{ f }}
                            </p>
                            <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}
                        <button type="submit" class="button-submit">Войти
                        </button>
                        <br>

                        <p class="p">Нет аккаунта? <a class="span" style="color: #0066ff"
                                                      href="{% url 'shop:register' %}">Зарегистрироваться
                        </a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <div style="height: 150px"></div>
{% endblock %}

shop/templates/shop/product/register.html
{% load static %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'shop/css/normalize.css' %}"/>
<link rel="icon" href="{% static 'shop/img/img.png' %}">
<style>
    body {
        background-color: #efefef;
        text-align: center;
    }

    h1 {
        text-align: center;
    }

    ::placeholder {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    }

    form {
        width: 100%;
        align-content: center;
        text-align: center;
    }

    .form-input {
        margin-left: 10px;
        border-radius: 10px;
        border: none;
        width: 100%;
        height: 100%;
    }

    .form-input:focus {
        outline: none;
    }

    .inputForm {
        border: 1.5px solid #ecedec;
        border-radius: 10px;
        height: 50px;
        display: flex;
        align-items: center;
        padding-left: 10px;
        transition: 0.2s ease-in-out;
    }

    .form-input {
        margin-left: 10px;
        border-radius: 10px;
        border: none;
        width: 70%;
        height: 100%;
    }

    .form-input:focus {
        outline: none;
    }

    .inputForm:focus-within {
        border: 1.5px solid #2d79f3;
    }

    .button-submit {
        margin: 20px 0 10px 0;
        background-color: #151717;
        border: none;
        color: white;
        font-size: 15px;
        font-weight: 500;
        border-radius: 10px;
        height: 50px;
        width: 100%;
        cursor: pointer;
    }

    .button-back {
        display: flex;
        height: 3em;
        width: 150px;
        align-items: center;
        justify-content: center;
        background-color: #efefef;
        border-radius: .60em;
        letter-spacing: 1px;
        transition: all 0.2s linear;
        cursor: pointer;
        border: none;
        background: #efefef;
        text-decoration: none;
    }

    .button-back > svg {
        margin-right: 5px;
        margin-left: 5px;
        font-size: 20px;
        transition: all 0.4s ease-in;
    }

    .button-back:hover > svg {
        font-size: 1.2em;
        transform: translateX(-5px);
    }

    .button-back:hover {
        box-shadow: 9px 9px 33px #d1d1d1, -9px -9px 33px #ffffff;
        transform: translateY(-2px);
    }
</style>
{% block content %}
    <div style="display: flex">
        <a class="button-back" href="{% url 'shop:catalog' %}" style="width: 300px; color: black">
            <svg height="16" width="16" xmlns="http://www.w3.org/2000/svg" version="1.1"
                 viewBox="0 0 1024 1024">
                <path d="M874.690416 495.52477c0 11.2973-9.168824 20.466124-20.466124 20.466124l-604.773963 0 188.083679 188.083679c7.992021 7.992021 7.992021 20.947078 0 28.939099-4.001127 3.990894-9.240455 5.996574-14.46955 5.996574-5.239328 0-10.478655-1.995447-14.479783-5.996574l-223.00912-223.00912c-3.837398-3.837398-5.996574-9.046027-5.996574-14.46955 0-5.433756 2.159176-10.632151 5.996574-14.46955l223.019353-223.029586c7.992021-7.992021 20.957311-7.992021 28.949332 0 7.992021 8.002254 7.992021 20.957311 0 28.949332l-188.073446 188.073446 604.753497 0C865.521592 475.058646 874.690416 484.217237 874.690416 495.52477z"></path>
            </svg>
            <span style="padding-left: 5px">Перейти к каталогу</span>
        </a></div>
    <div class="container" style="margin-top: 100px">
        <div class="row">
            <div class="login wrap">
                <h1 class="h1">Введите данные</h1>
                <br>
                <div style="display: flex; justify-content: center">
                    <form method="post"
                          style="display: flex;flex-direction: column;gap: 10px;background-color: #ffffff;padding: 30px;width: 50%;border-radius: 20px;font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
                        {% csrf_token %}
                        <!-- Отражение общих ошибок авторизации ползователей. Т.е. ошибки связанные не с заполнением полей, напр. неверные логин/пароль-->
                        <div class="form-error">{{ form.non_field_errors }}</div>
                        <!-- Конец -->
                        {% for f in form %}
                            <p class="inputForm">
                                <label class="form-label" for="{{ f.id_for_label }}"> {{ f.label }}: </label>{{ f }}
                            </p>
                            <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}
                        <button type="submit" class="button-submit">Зарегистрироваться
                        </button>
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <div style="height: 150px"></div>
{% endblock %}